import { CheckInQuestion, ConversationTopic, DiscoverQuestion, Achievement, Title } from "./types";

export const checkInQuestions: CheckInQuestion[] = [
  { id: "ci-1", question: "Did you ask her how her day was today?", type: "yesno", category: "communication" },
  { id: "ci-2", question: "Did you tell her something you appreciate about her?", type: "yesno", category: "appreciation" },
  { id: "ci-3", question: "Did you initiate physical affection today? (hug, kiss, hold hands)", type: "yesno", category: "physical" },
  { id: "ci-4", question: "Did you actively listen when she talked without checking your phone?", type: "yesno", category: "communication" },
  { id: "ci-5", question: "Did you do something small to make her smile?", type: "yesno", category: "emotional" },
  { id: "ci-6", question: "Rate how present you were with her today", type: "scale", category: "quality-time" },
  { id: "ci-7", question: "Did you ask her about something she mentioned earlier this week?", type: "yesno", category: "communication" },
  { id: "ci-8", question: "Did you compliment her today?", type: "yesno", category: "appreciation" },
  { id: "ci-9", question: "Did you suggest doing something together?", type: "yesno", category: "quality-time" },
  { id: "ci-10", question: "Did you check in on how she's feeling emotionally?", type: "yesno", category: "emotional" },
  { id: "ci-11", question: "Did you share something vulnerable about your own feelings?", type: "yesno", category: "emotional" },
  { id: "ci-12", question: "Did you notice if she seemed stressed or off today?", type: "yesno", category: "emotional" },
  { id: "ci-13", question: "Did you say 'I love you' and mean it fully?", type: "yesno", category: "appreciation" },
  { id: "ci-14", question: "Did you put your phone away during quality time?", type: "yesno", category: "quality-time" },
  { id: "ci-15", question: "Did you remember something important she told you and bring it up?", type: "yesno", category: "communication" },
  { id: "ci-16", question: "Did you surprise her with anything, even something tiny?", type: "yesno", category: "appreciation" },
  { id: "ci-17", question: "Rate how emotionally available you were today", type: "scale", category: "emotional" },
  { id: "ci-18", question: "Did you ask about her friends or family?", type: "yesno", category: "communication" },
  { id: "ci-19", question: "Did you make eye contact and really see her today?", type: "yesno", category: "emotional" },
  { id: "ci-20", question: "Did you help her with something without being asked?", type: "yesno", category: "appreciation" },
  { id: "ci-21", question: "What's one thing you noticed about her mood today?", type: "freeform", category: "emotional" },
  { id: "ci-22", question: "What's one thing she said today that you want to remember?", type: "freeform", category: "communication" },
  { id: "ci-23", question: "Did you make plans for something to look forward to together?", type: "yesno", category: "quality-time" },
  { id: "ci-24", question: "Did you express gratitude for something specific she does?", type: "yesno", category: "appreciation" },
  { id: "ci-25", question: "Rate your overall effort in the relationship today", type: "scale", category: "quality-time" },
];

export const conversationTopics: ConversationTopic[] = [
  { id: "ct-1", topic: "If money wasn't an issue, what would our life look like in 5 years?", description: "Explore shared dreams and see where your visions align", category: "future", depth: 2 },
  { id: "ct-2", topic: "What's a childhood memory that shaped who you are today?", description: "Understanding formative experiences builds deeper connection", category: "memories", depth: 2 },
  { id: "ct-3", topic: "What's your biggest fear about our relationship?", description: "Addressing fears together builds trust and security", category: "fears", depth: 3 },
  { id: "ct-4", topic: "What does feeling truly loved look like to you?", description: "Learn her love language at a deeper level", category: "emotional", depth: 3 },
  { id: "ct-5", topic: "If you could master any skill overnight, what would it be?", description: "Light but revealing — shows hidden passions", category: "dreams", depth: 1 },
  { id: "ct-6", topic: "What value do you think is most important to pass on to future kids?", description: "Reveals core beliefs and priorities", category: "values", depth: 2 },
  { id: "ct-7", topic: "What's a moment in your life you wish you could relive?", description: "Nostalgia opens emotional vulnerability", category: "memories", depth: 2 },
  { id: "ct-8", topic: "If we could live anywhere in the world for a year, where would you pick?", description: "Fun way to explore adventurous sides", category: "hypothetical", depth: 1 },
  { id: "ct-9", topic: "What's something you've never told anyone?", description: "Deep vulnerability builder — handle with care", category: "emotional", depth: 3 },
  { id: "ct-10", topic: "How do you want to be remembered?", description: "Gets to the core of someone's identity", category: "values", depth: 3 },
  { id: "ct-11", topic: "What's a dream you gave up on that you sometimes still think about?", description: "Revisiting lost dreams can be healing", category: "dreams", depth: 2 },
  { id: "ct-12", topic: "What makes you feel most alive?", description: "Understanding what energizes her", category: "emotional", depth: 2 },
  { id: "ct-13", topic: "If you could change one thing about how you were raised, what would it be?", description: "Reveals family dynamics and personal growth", category: "memories", depth: 3 },
  { id: "ct-14", topic: "What's a belief you held strongly that you've since changed your mind about?", description: "Shows intellectual growth and openness", category: "values", depth: 2 },
  { id: "ct-15", topic: "What would you do if you knew you couldn't fail?", description: "Removes fear from the equation to reveal true desires", category: "hypothetical", depth: 1 },
  { id: "ct-16", topic: "When do you feel most disconnected from me and why?", description: "Direct relationship improvement conversation", category: "emotional", depth: 3 },
  { id: "ct-17", topic: "What's a tradition you'd love for us to start?", description: "Building shared rituals strengthens bonds", category: "future", depth: 1 },
  { id: "ct-18", topic: "What's the bravest thing you've ever done?", description: "Celebrating courage opens admiration", category: "memories", depth: 2 },
  { id: "ct-19", topic: "If you could have dinner with anyone, dead or alive, who?", description: "Classic but always revealing", category: "hypothetical", depth: 1 },
  { id: "ct-20", topic: "What part of your personality do you wish more people understood?", description: "Helps you see her the way she wants to be seen", category: "emotional", depth: 3 },
  { id: "ct-21", topic: "What does your ideal weekend look like?", description: "Practical and reveals what recharges her", category: "future", depth: 1 },
  { id: "ct-22", topic: "What's something you think couples should talk about more?", description: "Meta-conversation about communication itself", category: "values", depth: 2 },
  { id: "ct-23", topic: "What's a turning point in your life that made you who you are?", description: "Deep identity exploration", category: "memories", depth: 3 },
  { id: "ct-24", topic: "What scares you about getting older?", description: "Vulnerability about mortality and change", category: "fears", depth: 3 },
  { id: "ct-25", topic: "What's the most romantic thing someone could do for you?", description: "Direct intel for being a better partner", category: "emotional", depth: 2 },
  { id: "ct-26", topic: "What role does spirituality or faith play in your life?", description: "Deep belief system exploration", category: "values", depth: 3 },
  { id: "ct-27", topic: "If our relationship had a theme song, what would it be?", description: "Fun and creative way to reflect on the relationship", category: "fun", depth: 1 },
  { id: "ct-28", topic: "What's the kindest thing a stranger ever did for you?", description: "Beautiful stories that reveal what she values", category: "memories", depth: 1 },
  { id: "ct-29", topic: "What do you need more of in your life right now?", description: "Practical check-in with emotional depth", category: "emotional", depth: 2 },
  { id: "ct-30", topic: "What's a promise you've made to yourself?", description: "Personal commitments reveal priorities", category: "values", depth: 2 },
];

export const discoverQuestions: DiscoverQuestion[] = [
  { id: "dq-1", question: "What was your favorite toy as a child?", category: "childhood" },
  { id: "dq-2", question: "What's your earliest memory?", category: "childhood" },
  { id: "dq-3", question: "What did you want to be when you grew up?", category: "childhood" },
  { id: "dq-4", question: "What was your favorite subject in school?", category: "childhood" },
  { id: "dq-5", question: "What's a game you loved playing as a kid?", category: "childhood" },
  { id: "dq-6", question: "Who is she closest to in her family?", category: "family" },
  { id: "dq-7", question: "What family tradition does she love most?", category: "family" },
  { id: "dq-8", question: "What's her relationship with her siblings like?", category: "family" },
  { id: "dq-9", question: "What did her parents teach her that stuck?", category: "family" },
  { id: "dq-10", question: "What's her favorite family memory?", category: "family" },
  { id: "dq-11", question: "What's her comfort food?", category: "preferences" },
  { id: "dq-12", question: "What's her favorite flower?", category: "preferences" },
  { id: "dq-13", question: "What kind of music does she listen to when she's sad?", category: "preferences" },
  { id: "dq-14", question: "What's her favorite season and why?", category: "preferences" },
  { id: "dq-15", question: "Coffee or tea? And how does she take it?", category: "preferences" },
  { id: "dq-16", question: "What's her favorite movie that she could watch on repeat?", category: "preferences" },
  { id: "dq-17", question: "What's her ideal vacation destination?", category: "preferences" },
  { id: "dq-18", question: "What scent does she love?", category: "preferences" },
  { id: "dq-19", question: "What's something she's always wanted to learn?", category: "dreams" },
  { id: "dq-20", question: "Where does she see herself in 10 years?", category: "dreams" },
  { id: "dq-21", question: "What's on her bucket list?", category: "dreams" },
  { id: "dq-22", question: "What job would she do if pay wasn't a factor?", category: "dreams" },
  { id: "dq-23", question: "What's a country she's dying to visit?", category: "dreams" },
  { id: "dq-24", question: "What's the most embarrassing thing that happened to her?", category: "past" },
  { id: "dq-25", question: "What's the hardest thing she's ever been through?", category: "past" },
  { id: "dq-26", question: "What's her proudest achievement?", category: "past" },
  { id: "dq-27", question: "What's a lesson she learned the hard way?", category: "past" },
  { id: "dq-28", question: "What was her first job?", category: "past" },
  { id: "dq-29", question: "What does she believe happens after death?", category: "beliefs" },
  { id: "dq-30", question: "What's a cause she cares deeply about?", category: "beliefs" },
  { id: "dq-31", question: "What does she think is the meaning of life?", category: "beliefs" },
  { id: "dq-32", question: "What does she value most in a friendship?", category: "beliefs" },
  { id: "dq-33", question: "What's her morning routine?", category: "daily-life" },
  { id: "dq-34", question: "What does she do to destress?", category: "daily-life" },
  { id: "dq-35", question: "What's the first thing she does when she wakes up?", category: "daily-life" },
  { id: "dq-36", question: "What does she think about before falling asleep?", category: "daily-life" },
  { id: "dq-37", question: "What's her guilty pleasure?", category: "daily-life" },
  { id: "dq-38", question: "What does she value most in our relationship?", category: "relationships" },
  { id: "dq-39", question: "What's her love language?", category: "relationships" },
  { id: "dq-40", question: "What makes her feel most secure in a relationship?", category: "relationships" },
  { id: "dq-41", question: "What's a deal-breaker for her in relationships?", category: "relationships" },
  { id: "dq-42", question: "How does she like to resolve conflicts?", category: "relationships" },
];

export const achievements: Achievement[] = [
  { id: "ach-1", name: "First Step", description: "Complete your first check-in", icon: "👣", xpReward: 20, condition: "totalCheckIns >= 1" },
  { id: "ach-2", name: "Week Warrior", description: "7-day check-in streak", icon: "🔥", xpReward: 50, condition: "streak >= 7" },
  { id: "ach-3", name: "Habit Formed", description: "30-day check-in streak", icon: "💎", xpReward: 200, condition: "streak >= 30" },
  { id: "ach-4", name: "Deep Diver", description: "Complete your first deep conversation", icon: "🌊", xpReward: 30, condition: "totalConversations >= 1" },
  { id: "ach-5", name: "Soul Explorer", description: "Complete 10 deep conversations", icon: "🧭", xpReward: 100, condition: "totalConversations >= 10" },
  { id: "ach-6", name: "Curious Mind", description: "Ask your first discover question", icon: "🔍", xpReward: 20, condition: "totalDiscovers >= 1" },
  { id: "ach-7", name: "Her Encyclopedia", description: "Complete 20 discover questions", icon: "📚", xpReward: 150, condition: "totalDiscovers >= 20" },
  { id: "ach-8", name: "Party Planner", description: "Plan your first celebration", icon: "🎉", xpReward: 50, condition: "celebrationsPlanned >= 1" },
  { id: "ach-9", name: "Celebration King", description: "Plan 5 celebrations", icon: "👑", xpReward: 150, condition: "celebrationsPlanned >= 5" },
  { id: "ach-10", name: "All-Rounder", description: "Use all 4 features at least once", icon: "⭐", xpReward: 100, condition: "totalCheckIns >= 1 && totalConversations >= 1 && totalDiscovers >= 1 && celebrationsPlanned >= 1" },
  { id: "ach-11", name: "Century", description: "Reach 100 total check-ins", icon: "💯", xpReward: 200, condition: "totalCheckIns >= 100" },
  { id: "ach-12", name: "Three Day Start", description: "3-day check-in streak", icon: "🌱", xpReward: 30, condition: "streak >= 3" },
];

export const titles: Title[] = [
  { name: "Rookie", minLevel: 1, emoji: "🌱" },
  { name: "Beginner", minLevel: 3, emoji: "🌿" },
  { name: "Attentive", minLevel: 5, emoji: "👀" },
  { name: "Thoughtful", minLevel: 8, emoji: "💭" },
  { name: "Caring", minLevel: 11, emoji: "💝" },
  { name: "Devoted", minLevel: 15, emoji: "💍" },
  { name: "Romance Master", minLevel: 20, emoji: "👑" },
];

export const defaultCelebrations = [
  {
    id: "cel-valentine",
    name: "Valentine's Day",
    date: "02-14",
    isRecurring: true,
    icon: "💘",
    giftIdeas: [
      "Handwritten love letter",
      "Surprise dinner reservation",
      "Photo album of your best moments",
      "Her favorite flowers with a personal note",
      "Plan a surprise experience (cooking class, spa day)",
      "Custom playlist of songs that remind you of her",
    ],
  },
  {
    id: "cel-womensday",
    name: "Women's Day",
    date: "03-08",
    isRecurring: true,
    icon: "🌸",
    giftIdeas: [
      "Flowers delivered to her workplace",
      "Celebrate the women in her life together",
      "Gift her a book by a female author she admires",
      "Plan a day where she doesn't have to do any chores",
      "Donate to a cause she cares about in her name",
    ],
  },
  {
    id: "cel-christmas",
    name: "Christmas",
    date: "12-25",
    isRecurring: true,
    icon: "🎄",
    giftIdeas: [
      "Thoughtful personalized gift",
      "Experience gift (concert, trip, workshop)",
      "Something she mentioned wanting months ago",
      "Matching couple items",
      "Create a Christmas tradition together",
      "Advent calendar with 24 small surprises",
    ],
  },
  {
    id: "cel-newyear",
    name: "New Year's Eve",
    date: "12-31",
    isRecurring: true,
    icon: "🎆",
    giftIdeas: [
      "Plan a special New Year's celebration",
      "Write her a letter about your favorite moments of the year",
      "Create a vision board together for the new year",
      "Midnight surprise (fireworks, champagne, rooftop)",
    ],
  },
];

export const XP_PER_CHECKIN = 10;
export const XP_PER_CONVERSATION = 25;
export const XP_PER_DISCOVER = 15;
export const XP_PER_CELEBRATION = 50;
export const XP_PER_LEVEL = 100;
